#!/usr/bin/env bash
# 1.4.0 — Codex AGENTS.md handoff.
#
# The codex-sessionstart-base-load flip stops the memory system from generating
# ~/.codex/AGENTS.md (the base now injects live via the SessionStart hook). Any
# instance that upgraded from a pre-1.4.0 codex install still has a machine-built
# AGENTS.md sitting on disk — a stale memory snapshot that would otherwise become
# the permanent static base. Convert it, in place, to a hand-owned file.
#
# Header-keyed and safe by construction: only a memory-generated AGENTS.md carries
# the `Generated by codex-mem` header, so a hand-owned file (no header) is left
# byte-identical. Forward-only, idempotent — a second run finds no header and does
# nothing.
set -euo pipefail

: "${MEMORY_DIR:?MEMORY_DIR is required}"
: "${REPO_ROOT:?REPO_ROOT is required}"

AGENTS="${CODEX_INSTRUCTIONS_FILE:-$HOME/.codex/AGENTS.md}"
OVERLAY="${CODEX_OVERLAY_FILE:-$HOME/.codex/AGENTS.local.md}"
HEADER_MARK="Generated by codex-mem"

# Nothing to convert if codex was never installed / the file is absent.
[ -f "$AGENTS" ] || exit 0

# Only a memory-generated file self-identifies. Absent header => hand-owned => leave it.
grep -q "$HEADER_MARK" "$AGENTS" || exit 0

# Generated file found. Seed the hand-owned base from the overlay the user kept
# (its whole reason for existing), else a stub. Write via a temp file so a failure
# never leaves a truncated AGENTS.md.
tmp="$AGENTS.handoff.$$"
if [ -f "$OVERLAY" ] && [ -s "$OVERLAY" ]; then
    cat "$OVERLAY" > "$tmp"
else
    cat > "$tmp" <<'STUB'
# Codex — hand-owned base

This file is yours to edit. The ai-memory system no longer regenerates it: the
memory tree (identity, project, index, domain, working) injects live via the
Codex SessionStart / UserPromptSubmit hooks. Put permanent Codex-specific
workflow rules or personal instructions here.
STUB
fi
mv "$tmp" "$AGENTS"

# The overlay existed only to survive AGENTS.md regeneration; that path is gone and
# nothing reads AGENTS.local.md any more. Its content is already folded into AGENTS.md
# above — retire the file (renamed, not deleted, so nothing is lost).
if [ -f "$OVERLAY" ]; then
    mv "$OVERLAY" "$OVERLAY.retired"
fi
