#!/usr/bin/env bash
# Antigravity launch wrapper (agy.sh): rebuilds the md context from the memory
# tree via the shared builder (generator label "agy"), then exec's agy with args
# passed through. Uses a stub `agy` on PATH so no real binary is needed.
. "$(dirname "$0")/_assert.sh"

REPO="$(cd "$SCRIPTS_DIR/.." && pwd)"
WRAP="$REPO/harnesses/antigravity/scripts/agy.sh"

MEM="$(new_sandbox)"; BIN="$(new_sandbox)"
trap 'rm -rf "$MEM" "$BIN"' EXIT
export MEMORY_DIR="$MEM"
seed_min_tree "$MEM"
mkdir -p "$MEM/projects/proj"
cat > "$MEM/projects/proj/memory.md" <<'EOF'
---
topic: proj
scope: project
summary: proj summary
---
# Project: proj
EOF
WORK="$MEM/work"; mkdir -p "$WORK/.agents"; printf 'proj\n' > "$WORK/.agents/memory-project"

# Stub agy that records its args.
CAP="$BIN/agy-args"
cat > "$BIN/agy" <<EOF
#!/usr/bin/env bash
printf '%s ' "\$@" > "$CAP"
exit 0
EOF
chmod +x "$BIN/agy"
export PATH="$BIN:$PATH"

CTX="$BIN/AGENTS.md"
export AGY_CONTEXT_FILE="$CTX"
export AGY_OVERLAY_FILE="$BIN/AGENTS.local.md"   # absent -> no overlay section

set +e
(cd "$WORK" && bash "$WRAP" -p "do the thing" --model gpt-x) >/dev/null 2>&1; CODE=$?
set -e
assert_exit 0 "$CODE" "agy.sh exits 0 via stub"
assert_file "$CTX" "agy.sh built the context file"

body="$(cat "$CTX")"
assert_contains "$body" "Generated by agy from"    "context header names the agy generator"
assert_contains "$body" "# === IDENTITY ==="       "context has identity section"
assert_contains "$body" "# === PROJECT: proj ==="  "context resolved the active project"

args="$(cat "$CAP")"
assert_contains "$args" "-p do the thing"  "agy.sh passes the prompt through"
assert_contains "$args" "--model gpt-x"    "agy.sh passes model flag through"

# --- missing agy binary -> clear error, no build ---
set +e
(PATH="/usr/bin:/bin" AGY_CONTEXT_FILE="$BIN/nope.md" bash "$WRAP" -p x) >/dev/null 2>&1; CODE=$?
set -e
assert_exit 1 "$CODE" "agy.sh errors when agy is absent"

finish
