#!/usr/bin/env bash
# build-context-md.sh — build the file-materialize markdown context (the
# AGENTS.md-style file a `file`-archetype harness reads at launch) from the
# memory tree. Shared by every per-harness launch wrapper so the build lives in
# ONE place: codex-mem.sh (Codex) and agy.sh (Antigravity) both call this.
#
#   build-context-md.sh <out-file> <generator-label> [overlay-file]
#
# <generator-label> names the wrapper in the generated header (e.g. codex-mem,
# agy). <overlay-file> is a user-owned file concatenated verbatim at the end and
# never written — omit it for a harness with no overlay concept.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/_lib.sh"
. "$SCRIPT_DIR/content-core.sh"
. "$SCRIPT_DIR/formatters/md.sh"

OUT="${1:?usage: build-context-md.sh <out-file> <generator-label> [overlay-file]}"
GEN="${2:?usage: build-context-md.sh <out-file> <generator-label> [overlay-file]}"
OVERLAY="${3:-}"

mkdir -p "$(dirname "$OUT")"
PROJECT="$(detect_active_project)"

{
    if [ -n "$OVERLAY" ]; then
        echo "<!-- Generated by $GEN from $MEMORY_DIR. Do not edit by hand."
        echo "     For permanent personal additions, edit $OVERLAY instead;"
        echo "     it is concatenated below the generated sections and never touched. -->"
    else
        echo "<!-- Generated by $GEN from $MEMORY_DIR. Do not edit by hand."
        echo "     Regenerated on each launch from the memory tree. -->"
    fi
    echo
    content_sections "$PROJECT" identity project index domain working | md_render
    if [ -n "$OVERLAY" ] && [ -f "$OVERLAY" ] && [ -s "$OVERLAY" ]; then
        echo "# === LOCAL OVERLAY ==="
        echo "<!-- Source: $OVERLAY (user-owned, never overwritten). -->"
        echo
        cat "$OVERLAY"
        echo
    fi
} > "$OUT"
