#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/_lib.sh"

CODEX_INSTRUCTIONS="${CODEX_INSTRUCTIONS_FILE:-$HOME/.codex/AGENTS.md}"
CODEX_OVERLAY="${CODEX_OVERLAY_FILE:-$HOME/.codex/AGENTS.local.md}"

if ! command -v codex >/dev/null 2>&1; then
    echo "codex-mem: codex not found in PATH" >&2
    exit 1
fi

# Executor shorthand: `codex-mem.sh --executor "<prompt>"` expands to the orchestrator-workflow
# default invocation — workspace-write sandbox, network on (for gh), no approval prompts.
# Deny rules in ~/.codex/rules/default.rules still block apply/merge/etc.
#
# `--executor-bare` is the same, minus the memory stack: it SKIPS the AGENTS.md
# merge below and sets `project_doc_max_bytes=0` so codex doesn't read AGENTS.md at
# all (~13k tokens stripped). Use it for read-only review/analysis subagents that
# don't need identity/project memory — keeps the orchestrator's fan-out lean. The
# deny-rules guardrails still apply (they load from ~/.codex/rules/, not AGENTS.md).
EXECUTOR_FLAGS=()
EXECUTOR_MODE=false
EXECUTOR_BARE=false
case "${1:-}" in
    --executor|--executor-bare)
        [ "$1" = "--executor-bare" ] && EXECUTOR_BARE=true
        shift
        EXECUTOR_MODE=true
        EXECUTOR_FLAGS=(
            exec
            --sandbox workspace-write
            --skip-git-repo-check
            -c sandbox_workspace_write.network_access=true
        )
        if [ "$EXECUTOR_BARE" = true ]; then
            EXECUTOR_FLAGS+=(-c project_doc_max_bytes=0)
        fi
        ;;
esac

# Bare executor skips the memory merge entirely (codex won't read AGENTS.md anyway).
if [ "$EXECUTOR_BARE" != true ]; then

mkdir -p "$(dirname "$CODEX_INSTRUCTIONS")"

PROJECT=$(detect_active_project)

# Compose merged instructions
{
    echo "<!-- Generated by codex-mem from $MEMORY_DIR. Do not edit by hand."
    echo "     For permanent personal additions, edit $CODEX_OVERLAY instead;"
    echo "     it is concatenated below the generated sections and never touched. -->"
    echo

    if [ -f "$MEMORY_DIR/identity.md" ]; then
        echo "# === IDENTITY ==="
        echo
        cat "$MEMORY_DIR/identity.md"
        echo
    fi

    if [ -n "$PROJECT" ] && [ -f "$MEMORY_DIR/projects/$PROJECT/memory.md" ]; then
        echo "# === PROJECT: $PROJECT ==="
        echo
        cat "$MEMORY_DIR/projects/$PROJECT/memory.md"
        echo
    fi

    if [ -f "$MEMORY_DIR/index.md" ]; then
        echo "# === MEMORY INDEX ==="
        echo
        cat "$MEMORY_DIR/index.md"
        echo
    fi

    # Frontmatter-driven Domain Index. Codex reads the file on demand.
    if [ -d "$MEMORY_DIR/domain" ]; then
        echo "# === DOMAIN INDEX ==="
        echo
        echo "Domain knowledge files live under \`$MEMORY_DIR/domain/\`. When the user's"
        echo "request matches a topic's triggers below, read the absolute path with your"
        echo "file-read tool BEFORE answering. Treat the file as authoritative over"
        echo "training defaults."
        echo
        echo "| File | Triggers | Summary |"
        echo "|------|----------|---------|"
        # Stable ordering so the generated file is reproducible.
        for f in $(find "$MEMORY_DIR/domain" -maxdepth 1 -type f -name '*.md' | sort); do
            topic=$(extract_fm_field "$f" "topic")
            triggers=$(extract_fm_field "$f" "triggers")
            summary=$(extract_fm_field "$f" "summary")
            # Normalize triggers for display: strip [ ] if present.
            triggers="${triggers#[}"
            triggers="${triggers%]}"
            # If a file lacks frontmatter, fall back to its basename + empty fields.
            [ -z "$topic" ] && topic=$(basename "$f" .md)
            [ -z "$summary" ] && summary="(no summary; add frontmatter)"
            echo "| $f | ${triggers:-—} | $summary |"
        done
        echo
    fi

    if [ -n "$PROJECT" ]; then
        WORKING="$MEMORY_DIR/projects/$PROJECT/working.md"
        if [ -f "$WORKING" ] && [ -s "$WORKING" ]; then
            echo "# === WORKING MEMORY ==="
            echo
            cat "$WORKING"
            echo
        fi
    fi

    if [ -f "$CODEX_OVERLAY" ] && [ -s "$CODEX_OVERLAY" ]; then
        echo "# === LOCAL OVERLAY ==="
        echo "<!-- Source: $CODEX_OVERLAY (user-owned, never overwritten). -->"
        echo
        cat "$CODEX_OVERLAY"
        echo
    fi
} > "$CODEX_INSTRUCTIONS"

fi  # end memory-merge (skipped for --executor-bare)

# In executor mode, redirect stdin from /dev/null so codex doesn't block waiting
# for stdin EOF when invoked from a harness that holds stdin open (e.g. via a
# unix socket peer). Interactive `codex-mem.sh` calls keep stdin inherited.
if [ "$EXECUTOR_MODE" = "true" ]; then
    exec codex ${EXECUTOR_FLAGS[@]+"${EXECUTOR_FLAGS[@]}"} "$@" </dev/null
else
    exec codex ${EXECUTOR_FLAGS[@]+"${EXECUTOR_FLAGS[@]}"} "$@"
fi
