#!/usr/bin/env bash
# regenerate-state.sh — derive an on-demand "In Flight" snapshot across all projects.
#
# Writes $MEMORY_DIR/state.md: one row per project (last touched | current goal |
# open todos), every column DERIVED from existing sources so it cannot drift —
# it is a projection like index.md, never hand-authored.
#
# This view is ON-DEMAND: it is NOT added to the SessionStart injection payload
# (that would fight depth-first / delegate-don't-load). Read it when you ask
# "what's on my plate?".
#
# Targets macOS bash 3.2: no associative arrays, no mapfile.
#
# Usage: regenerate-state.sh [--stdout]   (--stdout prints instead of writing the file)
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/_lib.sh"

STATE="$MEMORY_DIR/state.md"
TAB="$(printf '\t')"

# file_mtime <path> -> epoch seconds (empty if missing). macOS stat first, GNU fallback.
file_mtime() {
    [ -e "$1" ] || return 0
    stat -f %m "$1" 2>/dev/null || stat -c %Y "$1" 2>/dev/null
}

# project_mtime <projdir> -> newest mtime (epoch) among the files that signal activity.
# git log is deliberately NOT used: 13/14 real projects are gitignored, so it would
# be blank for the projects that matter. mtime works for all.
project_mtime() {
    local d="$1" max=0 f m
    for f in "$d/memory.md" "$d/todo.md" "$d/working.md" "$d"/plans/*.md; do
        [ -e "$f" ] || continue
        m="$(file_mtime "$f")"; [ -n "$m" ] || continue
        [ "$m" -gt "$max" ] && max="$m"
    done
    printf '%s' "$max"
}

# epoch_date <epoch> -> YYYY-MM-DD ('—' for 0/empty). macOS date -r, GNU fallback.
epoch_date() {
    [ "${1:-0}" -gt 0 ] 2>/dev/null || { printf '—'; return; }
    date -r "$1" +%F 2>/dev/null || date -d "@$1" +%F 2>/dev/null || printf '—'
}

# extract_goal <memory.md> -> first non-empty line under "## Current Goal" (empty if none).
extract_goal() {
    awk '
        /^## Current Goal[[:space:]]*$/ { f = 1; next }
        f && /^## / { exit }
        f && NF { sub(/^[[:space:]]+/, ""); print; exit }
    ' "$1"
}

# count_open_todos <todo.md> -> number of unchecked "- [ ]" boxes (0 if no file).
# Lines inside a fenced code block (``` … ```) are skipped — a "- [ ]" in an
# example is not a real open item.
count_open_todos() {
    [ -f "$1" ] || { printf '0'; return; }
    awk '
        /^[[:space:]]*```/ { fence = !fence; next }
        !fence && /^[[:space:]]*- \[ \]/ { n++ }
        END { print n + 0 }
    ' "$1"
}

# Sentinel category key that sorts AFTER any real (printable-ASCII) category under
# LC_ALL=C — '~' (0x7E) is greater than digits/letters — so uncategorized rows land
# last within the grouped table.
UNCAT_SORT='~~~uncategorized'

# $1 = optional category filter (empty = all projects, grouped by category).
emit() {
    local filter="$1"
    if [ -n "$filter" ]; then
        printf '# In Flight — %s\n\n' "$filter"
    else
        printf '# In Flight — derived state snapshot\n\n'
    fi
    printf '<!-- Generated by scripts/regenerate-state.sh. ON-DEMAND view — NOT auto-injected; do not edit by hand. Every column is derived from existing sources. -->\n\n'
    printf '| Category | Project | Last touched | Current goal | Open todos |\n'
    printf '|----------|---------|--------------|--------------|-----------:|\n'
    {
        for f in $(find "$MEMORY_DIR/projects" -mindepth 2 -maxdepth 2 -type f -name memory.md 2>/dev/null); do
            case "$f" in *"/_template/"*) continue ;; esac
            d="$(dirname "$f")"; name="$(basename "$d")"
            cat="$(extract_fm_field "$f" category)"
            # Filter to one category when asked; empty filter = everything.
            if [ -n "$filter" ] && [ "$cat" != "$filter" ]; then continue; fi
            ep="$(project_mtime "$d")"
            goal="$(extract_goal "$f")"; [ -n "$goal" ] || goal="—"
            # one line; escape table-breaking pipes; truncate for the row.
            goal="$(printf '%s' "$goal" | tr '\n' ' ' | sed 's/|/\\|/g')"
            [ "${#goal}" -gt 70 ] && goal="$(printf '%s' "$goal" | cut -c1-69)…"
            todos="$(count_open_todos "$d/todo.md")"
            catdisp="$cat"; [ -n "$catdisp" ] || catdisp="—"
            catsort="$cat"; [ -n "$catsort" ] || catsort="$UNCAT_SORT"
            # sort-key | display-category | mtime | name | goal | todos
            printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$catsort" "$catdisp" "$ep" "$name" "$goal" "$todos"
        done
    } | LC_ALL=C sort -t"$TAB" -k1,1 -k3,3rn | while IFS="$TAB" read -r catsort catdisp ep name goal todos; do
        printf '| %s | %s | %s | %s | %s |\n' "$catdisp" "$name" "$(epoch_date "$ep")" "$goal" "$todos"
    done
    printf '\n_Derived from each project'\''s `memory.md` (## Current Goal + category), `todo.md` (open boxes), and newest file mtime. Grouped by category (uncategorized last), newest first within each. On-demand; regenerate with `scripts/regenerate-state.sh`._\n'
}

# --- args: [<category>] [--stdout], in any order ---
CATEGORY_FILTER=""
STDOUT=0
while [ $# -gt 0 ]; do
    case "$1" in
        --stdout) STDOUT=1 ;;
        --) shift; [ -n "${1:-}" ] && CATEGORY_FILTER="$1"; break ;;
        -*) echo "regenerate-state: unknown option: $1" >&2; exit 2 ;;
        *)  if [ -z "$CATEGORY_FILTER" ]; then CATEGORY_FILTER="$1"
            else echo "regenerate-state: unexpected argument: $1" >&2; exit 2; fi ;;
    esac
    shift
done

if [ "$STDOUT" -eq 1 ]; then
    emit "$CATEGORY_FILTER"
    exit 0
fi
emit "$CATEGORY_FILTER" > "$STATE"
printf 'regenerate-state: wrote %s\n' "$STATE"
