#!/usr/bin/env bash
# regenerate-activity.sh — per-category activity report: the plans CREATED within a
# time window, grouped by category (client/group). For reviewing or invoicing a
# client's work over a period.
#
# The unit of work is a PLAN (each carries `created:` frontmatter), NOT a completed
# task — so this is fully decoupled from the task-provider backend. Both live plans
# (projects/<p>/plans/) and archived plans (projects/<p>/archive/plans/) are scanned:
# a plan created this month may already be done/archived. Reading archive/ here is an
# EXPLICIT, user-invoked report — the "never auto-read archive/" rule is about
# background loading, not a report the user asked for.
#
# Category values are per-instance PERSONAL data; the output artifact is gitignored.
#
# Usage:
#   regenerate-activity.sh <category> [--since <N>[d]] [--stdout]
#   regenerate-activity.sh --all       [--since <N>[d]] [--stdout]
# Default window: 30 days. Without --stdout the report is written to $MEMORY_DIR/activity.md.
#
# Targets macOS bash 3.2: no associative arrays, no mapfile.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/_lib.sh"

ACTIVITY="$MEMORY_DIR/activity.md"
TAB="$(printf '\t')"
# Sentinel category key that sorts AFTER any real (printable-ASCII) category under
# LC_ALL=C, so uncategorized plans land in the last section.
UNCAT_SORT='~~~uncategorized'
UNCAT_DISP='(uncategorized)'

# --- args: (<category> | --all) [--since <N>[d]] [--stdout] ---
SCOPE=""        # category filter (empty when --all)
ALL=0
SINCE=30
STDOUT=0
while [ $# -gt 0 ]; do
    case "$1" in
        --all)      ALL=1 ;;
        --since)    shift; SINCE="${1:-}" ;;
        --since=*)  SINCE="${1#--since=}" ;;
        --stdout)   STDOUT=1 ;;
        --)         shift; [ -n "${1:-}" ] && SCOPE="$1"; break ;;
        -*)         echo "regenerate-activity: unknown option: $1" >&2; exit 2 ;;
        *)          if [ -z "$SCOPE" ]; then SCOPE="$1"
                    else echo "regenerate-activity: unexpected argument: $1" >&2; exit 2; fi ;;
    esac
    shift
done

SINCE="${SINCE%d}"   # accept "30" or "30d"
case "$SINCE" in ''|*[!0-9]*) echo "regenerate-activity: --since needs a number of days" >&2; exit 2 ;; esac
if [ "$ALL" -eq 1 ] && [ -n "$SCOPE" ]; then
    echo "regenerate-activity: give a <category> OR --all, not both" >&2; exit 2
fi
if [ "$ALL" -eq 0 ] && [ -z "$SCOPE" ]; then
    echo "usage: regenerate-activity.sh (<category> | --all) [--since <N>[d]] [--stdout]" >&2; exit 2
fi

# Cutoff date (inclusive): plans created on or after this land in the window.
CUTOFF="$(date -v-"${SINCE}"d +%F 2>/dev/null || date -d "${SINCE} days ago" +%F 2>/dev/null)"
if [ -z "$CUTOFF" ]; then echo "regenerate-activity: could not compute cutoff date" >&2; exit 1; fi
CUTOFF_N="$(printf '%s' "$CUTOFF" | tr -d '-')"

# Emit one TSV row per in-window plan: catsort \t catdisp \t project \t plan \t created \t status
gen_rows() {
    local files f d proj cat catdisp catsort p created created_n plan status
    files="$(find "$MEMORY_DIR/projects" -mindepth 2 -maxdepth 2 -type f -name memory.md 2>/dev/null)" || files=""
    while IFS= read -r f; do
        [ -n "$f" ] || continue
        case "$f" in *"/_template/"*) continue ;; esac
        d="$(dirname "$f")"; proj="$(basename "$d")"
        cat="$(extract_fm_field "$f" category)"
        # Scope: a category filter keeps only that category; --all keeps everything.
        if [ "$ALL" -eq 0 ] && [ "$cat" != "$SCOPE" ]; then continue; fi
        catdisp="$cat"; [ -n "$catdisp" ] || catdisp="$UNCAT_DISP"
        catsort="$cat"; [ -n "$catsort" ] || catsort="$UNCAT_SORT"
        for p in "$d"/plans/*.md "$d"/archive/plans/*.md; do
            [ -e "$p" ] || continue
            created="$(extract_fm_field "$p" created)"
            [ -n "$created" ] || continue
            created_n="$(printf '%s' "$created" | tr -d '-')"
            case "$created_n" in ''|*[!0-9]*) continue ;; esac   # not a YYYY-MM-DD date
            [ "$created_n" -lt "$CUTOFF_N" ] && continue          # before window (inclusive cutoff)
            plan="$(extract_fm_field "$p" plan)"; [ -n "$plan" ] || plan="$(basename "$p" .md)"
            status="$(extract_fm_field "$p" status)"; [ -n "$status" ] || status="—"
            printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$catsort" "$catdisp" "$proj" "$plan" "$created" "$status"
        done
    done <<< "$files"
}

emit() {
    local label
    if [ "$ALL" -eq 1 ]; then label="all categories"; else label="$SCOPE"; fi
    printf '# Activity — %s\n\n' "$label"
    printf '<!-- Generated by scripts/regenerate-activity.sh. Plans CREATED in the window, grouped by category. PERSONAL (gitignored); do not edit by hand. -->\n\n'
    printf '_Plans created on or after %s (last %s days)._\n\n' "$CUTOFF" "$SINCE"
    # Group by category asc (uncategorized last), newest plan first within a group.
    gen_rows | LC_ALL=C sort -t"$TAB" -k1,1 -k5,5r | awk -v FS="$TAB" '
        {
            if ($2 != prev) {
                if (NR > 1) printf "_%d plan(s)._\n\n", gc
                printf "## %s\n\n", $2
                print "| Project | Plan | Created | Status |"
                print "|---------|------|---------|--------|"
                prev = $2; gc = 0
            }
            printf "| %s | %s | %s | %s |\n", $3, $4, $5, $6
            gc++; total++
        }
        END {
            if (NR == 0) { print "_No plans created in this window._" }
            else { printf "_%d plan(s)._\n\n\n_Total: %d plan(s) across the report._\n", gc, total }
        }
    '
}

if [ "$STDOUT" -eq 1 ]; then
    emit
    exit 0
fi
emit > "$ACTIVITY"
printf 'regenerate-activity: wrote %s\n' "$ACTIVITY"
