#!/usr/bin/env bash
# Rebuild $MEMORY_DIR/index.md from frontmatter in domain/*.md and projects/*/memory.md.
# Idempotent. Replaces content inside <!-- BEGIN AUTOGEN --> / <!-- END AUTOGEN -->;
# anything outside the fence is preserved verbatim. Creates the file (with fence) if
# missing.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/_lib.sh"

INDEX="$MEMORY_DIR/index.md"
BEGIN_MARK="<!-- BEGIN AUTOGEN -->"
END_MARK="<!-- END AUTOGEN -->"

# Emit the autogen block to stdout.
emit_autogen() {
    printf '%s\n' "$BEGIN_MARK"
    printf '<!-- Generated by scripts/regenerate-index.sh. Edits inside this block are lost on regenerate. -->\n\n'

    # Lean roster: name + summary only. Claude loads the active project's memory.md
    # via the hook, or derives projects/<name>/memory.md for any other; file
    # locations (repo_path, etc.) come from inside that memory.md.
    printf '## Projects\n\n'
    printf '| Project | Summary |\n'
    printf '|---------|---------|\n'
    for f in $(find "$MEMORY_DIR/projects" -mindepth 2 -maxdepth 2 -type f -name 'memory.md' 2>/dev/null | sort); do
        # Skip _template — it's a scaffold, not an active project.
        case "$f" in *"/_template/"*) continue;; esac
        name=$(basename "$(dirname "$f")")
        summary=$(extract_fm_field "$f" "summary")
        [ -z "$summary" ] && summary="(no summary; add frontmatter)"
        printf '| %s | %s |\n' "$name" "$summary"
    done
    printf '\n'

    # Domain: topic + triggers + summary. Path is derivable as domain/<topic>.md.
    printf '## Domain\n\n'
    printf '| Topic | Triggers | Summary |\n'
    printf '|-------|----------|---------|\n'
    if [ -d "$MEMORY_DIR/domain" ]; then
        for f in $(find "$MEMORY_DIR/domain" -maxdepth 1 -type f -name '*.md' | sort); do
            case "$f" in */_template.md) continue;; esac
            topic=$(extract_fm_field "$f" "topic")
            triggers=$(extract_fm_field "$f" "triggers")
            summary=$(extract_fm_field "$f" "summary")
            triggers="${triggers#[}"
            triggers="${triggers%]}"
            [ -z "$topic" ] && topic="$(basename "$f" .md)"
            [ -z "$summary" ] && summary="(no summary; add frontmatter)"
            printf '| %s | %s | %s |\n' "$topic" "${triggers:-—}" "$summary"
        done
    fi
    printf '\n'

    printf '%s\n' "$END_MARK"
}

# If the index doesn't exist yet, write the autogen block on its own.
if [ ! -f "$INDEX" ]; then
    emit_autogen > "$INDEX"
    echo "regenerate-index: created $INDEX"
    exit 0
fi

# If the fence isn't present, append it to the end of the existing file.
if ! grep -qF "$BEGIN_MARK" "$INDEX"; then
    {
        cat "$INDEX"
        printf '\n'
        emit_autogen
    } > "$INDEX.tmp"
    mv "$INDEX.tmp" "$INDEX"
    echo "regenerate-index: added autogen fence to $INDEX"
    exit 0
fi

# Replace only the content between markers. Use awk to split.
awk -v begin="$BEGIN_MARK" -v end="$END_MARK" '
    BEGIN { in_block = 0 }
    $0 == begin { print; in_block = 1; printed_placeholder = 0; next }
    $0 == end {
        if (in_block && !printed_placeholder) { print "__AUTOGEN_REPLACE__" }
        in_block = 0
        print
        next
    }
    in_block {
        if (!printed_placeholder) { print "__AUTOGEN_REPLACE__"; printed_placeholder = 1 }
        next
    }
    { print }
' "$INDEX" > "$INDEX.tmp1"

# Now substitute __AUTOGEN_REPLACE__ with the new content. Build the new content
# without the fence lines (the original fence lines are preserved in $INDEX.tmp1).
emit_autogen \
    | awk -v begin="$BEGIN_MARK" -v end="$END_MARK" '
        $0 == begin { next }
        $0 == end { next }
        { print }
    ' > "$INDEX.body"

awk -v body_file="$INDEX.body" '
    BEGIN {
        while ((getline line < body_file) > 0) {
            body = (body == "" ? line : body ORS line)
        }
        close(body_file)
    }
    /^__AUTOGEN_REPLACE__$/ { print body; next }
    { print }
' "$INDEX.tmp1" > "$INDEX.tmp2"

mv "$INDEX.tmp2" "$INDEX"
rm -f "$INDEX.tmp1" "$INDEX.body"

echo "regenerate-index: refreshed autogen block in $INDEX"
